### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by jpsc** [voorhoede/mindspace#2]
Nice to have:
- [ ] font load improvements
- [ ] lazy load member list
- [ ] picturefill for mobile smaller images
